### PR TITLE
UF-181 add payment success and fail page

### LINKED ISSUE #152: add-payment-success-and-fail-page
*작업 설명*

결제 과정 중 성공 및 실패를 나타내는 페이지를 구현합니다.

*To-do*

* 계좌 등록 성공 페이지
* 결제 성공 페이지
* 결제 실패 페이지

### PR DESCRIPTION
**Pull request by abyss-s**
### #️⃣ 연관된 이슈

> close: #152 

### 🔎 작업 내용

- [x] 결제 수단 등록 성공 페이지 구현
- [x] 결제 성공 및 실패 페이지 구현
- [x] 배경 프로바이더 높이 및 배경이 채워지지 않는 버그 수정

### 📸 스크린샷 (선택)
스크린샷 2025-07-16 오후 7 10 00
스크린샷 2025-07-16 오후 7 16 35
스크린샷 2025-07-16 오후 7 26 07

## ✅ Check List

- [x] 관련 이슈를 등록하고 연결했나요?
- [x] 커밋 메시지 및 PR 제목이 컨벤션을 따랐나요?
- [x] 리뷰어가 이해할 수 있도록 충분한 설명이 작성되었나요?

___

### **PR Type**
Enhancement

___

### **Description**
- 결제 성공 및 실패 페이지 추가

- 계좌 등록 성공 페이지 구현

- 이미지 및 아이콘 추가

- 배경 프로바이더 수정

___

### **Changes diagram**

```mermaid
flowchart LR
  A["결제 성공 페이지 추가"] --> B["계좌 등록 성공 페이지 구현"]
  A --> C["결제 실패 페이지 추가"]
  D["이미지 및 아이콘 추가"] --> A
  E["배경 프로바이더 수정"] --> A
```

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>9 files</summary><table>
<tr>
  <td><strong>layout.tsx</strong><dd><code>계좌 등록 성공 페이지 레이아웃 추가</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-9b95569eb0c0a1acff8a65d1ffd458376df459f59197b558ebaea064bcf76b24">+11/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>page.tsx</strong><dd><code>계좌 등록 성공 페이지 구현</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-68424f03dfcaca9d84bb234f2747f178c09761897b2b0caf6b080342e3fe726b">+43/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>layout.tsx</strong><dd><code>결제 실패 페이지 레이아웃 추가</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-0963f4aac194f135d28ee387e1ee5f0d199797549033eae622a7dee662e91ffd">+11/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>page.tsx</strong><dd><code>결제 실패 페이지 구현</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-67a671c23b0d67dffdfb24a81627fbd56bcccf3e9ea6c3dfb71ea6a6fb209b61">+35/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>layout.tsx</strong><dd><code>결제 성공 페이지 레이아웃 추가</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-e443bfd8f5ca4648db2c2bd3b5d9bd805aefcffded0997e7290135974120dd9b">+11/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>page.tsx</strong><dd><code>결제 성공 페이지 구현</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-aceb7860bfe534b12cb65f6cd8773105d45a4c82db785c070a1f23f997d40743">+35/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>images.ts</strong><dd><code>결제 관련 이미지 경로 추가</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-75e66535a9b4da2652a2296d637e3ec8e09730a3fef3e6c3e728ed960a9d90db">+3/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>BackgroundProvider.tsx</strong><dd><code>배경 프로바이더 수정</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-8269fbb702ccb57f3e02bfa21e54922d51244d142f8f6b903a75bd60fa83bc41">+13/-2</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td><strong>Icons.types.ts</strong><dd><code>경고 아이콘 타입 추가</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
  <td><a href="https://github.com/Ureca-Final-Project-Team1/UFO-Fi-FE/pull/158/files#diff-91385a8c38ae3fb0ebc0e76991f3c74871727d07d64b803647f5a27ef49e44d4">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></details></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about PR-Agent usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

File: src/app/payment/account/success/page.tsx [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+  return (
+    <div className="flex flex-col h-full w-full">
+      <Title title="" iconVariant="close" />
+      <div className="flex-1 flex flex-col items-center justify-center px-6">
+        <div
+          className={`flex flex-col items-center text-center ${isMobile ? 'space-y-4' : 'space-y-6'}`}
+        >
+          <Image
+            src={IMAGE_PATHS['PAYMENT_CHECK']}
+            alt="Blackhole"
```
Comment (minji-38) [inline src/app/payment/account/success/page.tsx]: 결제 성공 페이지고 체크 아이콘 이미지인데 alt 설명에는 Balckhole이라고 적혀있어요! 변경 부탁드립니다~

File: src/app/payment/account/success/page.tsx [hunk 2]
```diff
@@ -0,0 +1,43 @@
+'use client';
+
+import Image from 'next/image';
+// import { useRouter } from 'next/navigation';
+
+import { IMAGE_PATHS } from '@/constants/images';
+import { Button, Title } from '@/shared/ui';
+import { useViewportStore } from '@/stores/useViewportStore';
+
+export default function BlackholePage() {
```
Comment (minji-38) [inline src/app/payment/account/success/page.tsx]: 지금 올려주신 page들이 다 BalckholePage로 되어있는데 의도하신 걸까요?

**Review by minji-38 — COMMENTED** [review]
리뷰 확인 부탁드립니다~

File: src/app/payment/account/success/page.tsx (hunk 1 above)
Comment (minji-38) [reply src/app/payment/account/success/page.tsx]: 의도하신 걸까요?

File: src/app/payment/account/success/page.tsx (hunk 2 above)
Comment (abyss-s) [reply src/app/payment/account/success/page.tsx]: 앗 제가 해당 페이지를 복붙해서 사용하다보니 페이지 컴포넌트 명을 미처 다 수정못했네요..😳 
바로 수정하겠습니다!

**Comment by abyss-s** [comment]
> @minji-38 수정사항 반영 완료했습니다 :)

**Review by minji-38 — APPROVED** [review]
머지하겠습니다~
